[model]
# config = "/data/metadata/output/miniyulan-2B-final-stage16-nooptim/checkpoint-155587"
# config = "/data/flame/configs/transformer_340M.json"
config = "${CONFIG}"
tokenizer_path = "/data/metadata/output/miniyulan-2B-final-stage16-nooptim/checkpoint-155587"
# converters = "float8"  #  swap nn.Linear with Float8Linear to perform float8 matmul.

[job]
print_args = true

[training]
batch_size = ${BATCH_SIZE}
seq_len = ${SEQ_LEN}
context_len = ${SEQ_LEN}
warmup_steps = ${WARMUP_STEPS}
gradient_accumulation_steps = ${GAS}
# steps = ${STEPS}
max_norm = 1.0
skip_nan_inf = true
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "/data/hf_dataset/myl_new_no_math/17_20241108_004951"
dataset_name = "default"
num_workers = 32
pin_memory = true
persistent_workers = false
prefetch_factor = 2
seed = 42
varlen = false

[optimizer]
name = "AdamW"
eps = 1e-15
fused = true
lr = ${LR}
min_lr_ratio = 0.1
scheduler = 'constant'
early_step_in_backward = true

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 256
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "async"    # ["disabled", "async", "async_with_pinned_mem"]
load_step = ${LOAD_STEP}

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 32

[metrics]
log_freq = 1
enable_wandb = true

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_compiled_autograd = false
expert_parallel_degree = 4

[float8]
enable_fsdp_float8_all_gather = true  # cast Float8Linear.weight from high precision to float8 before FSDP all-gather so we can communicate in float8 to save bandwidth.
precompute_float8_dynamic_scale_for_fsdp = true  # communicate AMAX/scales efficiently in a single all-reduce for all parameters instead of doing many small all-reduce for each parameter.
force_recompute_fp8_weight_in_bwd = true  # force recomputation of fp8 weights during backward pass, preventing unsharded fp8 weights from being saved for backward.

[activation_checkpoint]
mode = "full"  # ['none', 'full', 'selective']
# selective_ac_option = "54/56"